// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Musiora",
    platforms: [
        .iOS("18.0")
    ],
    products: [
        .iOSApplication(
            name: "Musiora",
            targets: ["AppModule"],
            bundleIdentifier: "DGG.Musiora",
            teamIdentifier: "5J67QYYC28",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .boat),
            accentColor: .presetColor(.orange),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .camera(purposeString: "Musiora needs the camera to detect your body")
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("Audio/pulse.aif"),
                .process("Audio/offbeat.aif"),
                .process("Audio/melody.aif"),
                .process("Audio/accent.aif"),
            ]
        )
    ],
    swiftLanguageVersions: [.version("6")]
)